services:
  hb_cinema:
    image: booooo226a/hb_cinema_backend:latest
    container_name: Backend_Spring
    ports:
      - "80:8081"
    networks:
      - cinema_net
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
      VNPAY_TMN_CODE: ${VNPAY_TMN_CODE:-58X4B4HP}
      VNPAY_SECRET_KEY: ${VNPAY_SECRET_KEY}
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL:-http://localhost:3000/identity/payment/vn-pay-callback}
      TZ: Asia/Ho_Chi_Minh

networks:
  cinema_net:
    driver: bridge
