apiVersion: v1
kind: ConfigMap
metadata:
  name: hb-cinema-config
data:
  VNPAY_RETURN_URL: "http://localhost:3000/identity/payment/vn-pay-callback"
  VNPAY_TMN_CODE: "58X4B4HP"
  TZ: "Asia/Ho_Chi_Minh"
