apiVersion: v1
kind: Secret
metadata:
  name: hb-cinema-secrets
type: Opaque
stringData:
  # Trong môi trường thực tế, các giá trị này thường được mã hóa Base64
  # Dùng 'stringData' để K8s tự động mã hóa cho mình lúc deploy
  DB_URL: "jdbc:mysql://hb-cinema-db.crwsmw6e2qol.us-east-2.rds.amazonaws.com:3306/hb_cinema_db"
  DB_USERNAME: "admin"
  DB_PASSWORD: "YOUR_DB_PASSWORD"
  JWT_SIGNER_KEY: "YOUR_JWT_SECRET_KEY"
  VNPAY_SECRET_KEY: "YOUR_VNPAY_SECRET_KEY"
